### ISSUE TITLE
API docs not generated

### ISSUE THREAD

**Issue by aawdls** [DiamondLightSource/coniql#29]
The API page in the docs isn't populated https://coniql.readthedocs.io/en/latest/reference/api.html 

I guess we intend to move to github pages - this is one to look at then.

**Comment by aawdls** [comment]
Skeleton will bring GH pages support and updated docs structure.

**Comment by rjwills28** [comment]
Look like this has been fixed in move to skeleton. API page is populated at https://diamondlightsource.github.io/coniql/main/reference/api.html.
