### ISSUE TITLE
Memory leak when subscribing to many PVs updating at high rates

### ISSUE THREAD

**Issue by rjwills28** [DiamondLightSource/coniql#38]
I noticed while testing both the new Strawberry API implementation and 'original' Coniql that there is another memory leak when subscribing to many PVs updating at 10Hz. I was using some of the cs-web-proto performance tests where I monitor 100 unique PVs updating at 10Hz. In a test I increased the number of PVs to 200 and that is when I noticed that the Coniql server starts to leak memory.

**Comment by rjwills28** [comment]
I did a very quick debug and I was able to pinpoint what is happening. Essentially the PV updates are coming into the Coniql application too fast for it to manage. Each event gets added to a queue in the [caplugin.subscribe_channel()](https://github.com/dls-controls/coniql/blob/f9a05b6a76a242740d9aae18b0244f147260491e/src/coniql/caplugin.py#L191) method. This then gets processed and sent via the GraphQL subscription. However I noticed that the with 200 PVs, this queue continues to grow, leading to a memory leak. Note that with 100 PVs, Coniql can keep up and the queue size remains at 0. This implies that our processing is taking too long.

We need to think about how to handle this case. Ideally it would be good if we could optimise the processing to speed it up.
A quick fix (just to demo that this is the cause of the problem) is to empty the queue when it starts to build up, however this of course means that you will start missing PV updates.

**Comment by coretl** [comment]
We do this update squashing with a deque in aioca: https://github.com/dls-controls/aioca/blob/master/aioca/_catools.py#L415

We could do a similar thing here, have a deque of length 1 each for both value and metadata updates, and an event to signal that both should be checked and consumed

Another thing to do is profile what is slow. I suggest using https://pypi.org/project/py-spy/

**Comment by coretl** [comment]
FYI @ajgdls is doing some benchmarking of CA libraries at the moment

**Comment by rjwills28** [comment]
Fixed in move to Strawberry API PR #44 .
