### ISSUE TITLE
Consider connection pooling

### ISSUE THREAD

**Issue by aawdls** [DiamondLightSource/coniql#50]
When multiple clients subscribe to the same PV we would ideally avoid creating multiple monitor channels to the control system. This could make us look a bit more like a gateway, and e.g. provide some protection to the control system from a proliferation of duplicated clients (either accidental or malicious).

This may already be happening silently within the CA library: confirm whether this is the case. Could be done empirically by counting channels while increasing subscriptions.

If not, propose an implementation for this in coniql.

**Comment by coretl** [comment]
We did a test for ophyd that showed that connection caching is _not_ happening in the CA library, so we will have to do this at the application layer

**Comment by AlexanderWells-diamond** [comment]
This was done as part of PR https://github.com/DiamondLightSource/coniql/pull/94. We now pool camonitor connections in Coniql.
