### ISSUE TITLE
Intermittent CI test failures

### ISSUE THREAD

**Issue by rjwills28** [DiamondLightSource/coniql#64]
It was noticed that a specific test fails intermittently in the CI (e.g. [failed-test](https://github.com/DiamondLightSource/coniql/actions/runs/5066790168/jobs/9097032906)). 

The test in question creates a subscription and collects the responses for 0.5 secs. In this time it should collect 3 updates due to the update rate of the underlying PV it is monitoring (see [here](https://github.com/DiamondLightSource/coniql/blob/main/tests/test_aiohttp.py#L138)). However, it is possible that lags in the CI could mean that only 2 updates are registered and hence the test fails. This test may need to be re-thought so it is less dependent on timings.

However, it was also noted that it is only the subscription test using the newer 'graphql_transport_ws' protocol that has this problem, as the same test using the 'graphql_ws' protocol always passes. This suggests there could be a slowdown somewhere in the Strawberry code causing this. This should be investigated.

**Comment by AlexanderWells-diamond** [comment]
Just had another failed test: https://github.com/DiamondLightSource/coniql/actions/runs/5079016001/jobs/9124233505

It does seem most likely that it's a Strawberry issue, given the equivalent passing test means we can likely rule out the runner itself being too slow and e.g not updating the IOC itself frequently enough. 

It may be interesting to run the existing benchmark tests against Strawberry, and swap the protocol they use between the two options and observe the results.

**Comment by rjwills28** [comment]
I have had a closer look at this and I can confirm that there is NOT a problem with the new websocket protocol (i.e. graphql_transport_ws). This is because it is NOT the case that only the new websocket tests fail. The bias that we see here is that the first of the websockets protocols in the parametrised test fails. A simple tests of switching these around so that the old ws protocol goes first shows that this then becomes the test to fail. 

The problem here is a timing issue. The IOC starts up at the beginning of the set of tests. By the time we get to the subscription test, the PV that is updating at 2Hz is no longer at 0. To make the test checks easier, we do a `caput` to reset the value to _0_ and then collect results. However depending on the timings, sometimes the `caput` can put the value back to _0_, milliseconds before it is time to update to _1_ and so it is possible that we miss the update to _1_. Note that the _caplugin_ test also suffers from this problem.

We need to make this test more robust by removing the need to do a `caput` to reset to _0_. Instead we should use `caget` to get the value (_X_) when we start collecting results and compare against some expected results based on a starting value of _X_, i.e. expect results to be _X_, _X+1_, _X+2_.

PR coming...

**Comment by rjwills28** [comment]
Fixed in PR #76 .
